### ISSUE TITLE
p1 - マシン名を変える

### ISSUE THREAD

**Issue by corvvs** [nakamo326/iot#2]
`v.name`がマシン名。それぞれ `ynakamotS`と`yokawadaSW`にする。

**Comment by nakamo326** [comment]
https://github.com/nakamo326/iot/blob/8139f82ec6c418e4131fe60204adcc3fcd08ab48/p1/Vagrantfile#L9

変更が必要なのはこっちの`"server"`の部分みたい
Subjectの例であるようなvagrant ssh ~~Sみたいなコマンドはこっちの命名が参照されるようなので
v.nameのほうはvirtualbox内での仮想マシン名であって、Vagrantの仮想マシン名は config.vm.define "machine_name" do |server| で指定するという解釈のほうがよさそう
