### ISSUE TITLE
P2!!

### ISSUE THREAD

**Issue by corvvs** [nakamo326/iot#4]

**Comment by nakamo326** [comment]
TODO:
- [x] マシン名は”ログイン名S”にする
- [ ] 3つのwebアプリケーションを選定する
- [ ] 192.168.56.110にリクエストを送るときのHostの指定に応じで、webアプリケーションにルーティングする
  - [ ] `Host: app1.com` -> app1
  - [ ] `Host: app2.com` -> app2
  - [ ] それ以外はデフォルトでapp3
- [ ] app2は3つのレプリカを構成する
